name: Create Card From PR

on:
  pull_request:
    types: [opened]

jobs:
  create-pull-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run
        env:
          TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_ID_LIST: ${{ secrets.TRELLO_ID_LIST }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: user
          GH_REPO: repo
          ACTION: pull
        run: go run cmd/create/main.go
