name: delete-card
on:
  issues:
    types:
      - deleted
      - closed
  pull_request:
    types:
      - closed
jobs:
  delete-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go run cmd/delete/main.go