name: Update Trello Card

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

env:
  TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
  TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
  TRELLO_ID_BOARD: ${{ secrets.TRELLO_ID_BOARD }}
  TRELLO_ID_LIST: ${{ secrets.TRELLO_ID_LIST }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_USER: username
  GH_REPO: repository

jobs:
  issue-card:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: go run cmd/update/main.go
        env:
          GH_EVENT: ${{ github.event_name }}
          GH_ID: ${{ github.issues.id }}
  pull-card:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: go run cmd/update/main.go
        env:
          GH_EVENT: ${{ github.event_name }}
          GH_ID: ${{ github.pull_request.id }}